# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(398, 285)
        MainWindow.setMaximumSize(QtCore.QSize(398, 285))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.add_teacher_btn = QtWidgets.QPushButton(self.centralwidget)
        self.add_teacher_btn.setGeometry(QtCore.QRect(0, 0, 151, 51))
        self.add_teacher_btn.setObjectName("add_teacher_btn")
        self.add_student_btn = QtWidgets.QPushButton(self.centralwidget)
        self.add_student_btn.setGeometry(QtCore.QRect(0, 70, 151, 51))
        self.add_student_btn.setObjectName("add_student_btn")
        self.add_qstn_btn = QtWidgets.QPushButton(self.centralwidget)
        self.add_qstn_btn.setGeometry(QtCore.QRect(220, 0, 151, 51))
        self.add_qstn_btn.setObjectName("add_qstn_btn")
        self.add_test_btn = QtWidgets.QPushButton(self.centralwidget)
        self.add_test_btn.setGeometry(QtCore.QRect(220, 70, 151, 51))
        self.add_test_btn.setObjectName("add_test_btn")
        self.set_test_btn = QtWidgets.QPushButton(self.centralwidget)
        self.set_test_btn.setGeometry(QtCore.QRect(120, 160, 131, 51))
        self.set_test_btn.setObjectName("set_test_btn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 398, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.add_teacher_btn.setText(_translate("MainWindow", "Добавить учителя"))
        self.add_student_btn.setText(_translate("MainWindow", "Добавить ученика"))
        self.add_qstn_btn.setText(_translate("MainWindow", "Создать вопрос"))
        self.add_test_btn.setText(_translate("MainWindow", "Создать тест"))
        self.set_test_btn.setText(_translate("MainWindow", "Назначить тест"))
